service: serverless-rest-api
frameworkVersion: '4.x'
provider:
  name: aws
  runtime: provided.al2023
  region: us-east-1
  stage: ${opt:stage}
functions:
  api:
    handler: bin/main
    events: 
      - http:
          path: /ping
          method: GET
package:
  patterns:
    - '!*/**'
    - bin/main

